[Provider]
Name=PasskeyTestProvider
ID=test-provider
DBusName=fi.cmouse.PasskeyBroker.TestProvider
ObjectPath=/fi/cmouse/PasskeyBroker/TestProvider
Transports=internal
SupportedAlgorithms=-7
Priority=50
